### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by jamadden** [NextThought/nti.externalization#36]
It would be nice to have a standard set of benchmarks we can run to tell if we're getting faster or slower. 

The starting comparison point would be before #31 and #32, since I did some performance work already in those two.

**Comment by jamadden** [comment]
With the addition of the user profile benchmarks, I think we have a decent overall set of benchmarks. We can add more case-specific ones as we look for more bottlenecks.

Here's current results of Python 2.7, 1.0a1 vs 1.0a3. I think there's some pretty substantial, realistic improvements there.

| Benchmark                                                                                         | 27_10a1 | 27_binding_default           |
|---------------------------------------------------------------------------------------------------|---------|------------------------------|
| Construct Singleton                                                                               | 282 ns  | 138 ns: 2.05x faster (-51%)  |
| Construct Singleton with args                                                                     | 294 ns  | 157 ns: 1.88x faster (-47%)  |
| .bm_simple_iface: toExternalObject                            | 59.2 us | 36.7 us: 1.61x faster (-38%) |
| .bm_simple_iface: fromExternalObject                          | 107 us  | 72.5 us: 1.48x faster (-32%) |
| .bm_user_profile: toExternalObject                            | 391 us  | 237 us: 1.65x faster (-39%)  |
| .bm_user_profile: fromExternalObject                          | 3.01 ms | 1.86 ms: 1.62x faster (-38%) |
| .bm_simple_iface_list: toExternalObject                       | 593 us  | 395 us: 1.50x faster (-33%)  |
| .bm_simple_iface_list: fromExternalObject                     | 1.80 ms | 1.26 ms: 1.43x faster (-30%) |
| .bm_simple_registered_class: toExternalObject                 | 48.8 us | 30.6 us: 1.60x faster (-37%) |
| .bm_simple_registered_class: fromExternalObject               | 19.4 us | 13.4 us: 1.45x faster (-31%) |
| .bm_simple_registered_class: fromExternalObject (no args)     | 37.1 us | 24.4 us: 1.52x faster (-34%) |
| .bm_simple_registered_class: fromExternalObject (context arg) | 36.5 us | 24.3 us: 1.50x faster (-33%) |
| .bm_simple_registered_class: fromExternalObject (ds arg)      | 37.1 us | 24.3 us: 1.52x faster (-34%) |

**Comment by jzuech3** [comment]
👍
