### ISSUE TITLE
Stop subclassing PersistentPropertyHolder

### ISSUE THREAD

**Issue by jamadden** [NextThought/nti.externalization#43]
The datastructures in `nti.externalization.persistent` subclass `nti.zodb.persistentproperty.PersistentPropertyHolder`. 

I don't see a very good reason for them to do that: they are containers, and as such really shouldn't typically have their own properties, just contained objects.

I didn't find anything in our internal code (what I have checked out anyway) that actually uses them, except for nti.dublincore.datastructures, which subclasses one of them: but it subclasses `PersistentPropertyHolder` in another indirect way anyway! (Not that I could find where that new datastructure was being used).

Can we make them stop doing this? Not only would that let us drop our dependency on nti.zodb, it would also potentially make these objects faster (the shorter the mro, the faster it is to find---or fail to find---attributes). (Of course, nti.dublincore is monkey-patching them again, so that really is a theoretical benefit.)

**Comment by papachoco** [comment]
nti.dublincore is the only place we use the nti.externalization.persistent classes. Let me know when want to drop them and I can add  modify lines like the one below. ( I guess I I just need to add the PersistentPropertyHolder bases to it)

# For BWC, we apply these properties to the base class too,
# but the implementation is not correct as they do not get updated...
_PersistentExternalizableList.__bases__ = (PersistentCreatedModDateTrackingObject,) + \
                                                                      _PersistentExternalizableList.__bases__

**Comment by jamadden** [comment]
`PersistentCreatedModDateTrackingObject` is already a `PersistentPropertyHolder`, so no changes should be necessary.

**Comment by papachoco** [comment]
Cool .. let's drop it 📄
