### ISSUE TITLE
Remove `except POSKeyError` from choose_field

### ISSUE THREAD

**Issue by jamadden** [NextThought/nti.externalization#60]
choose_field is a hot function with an inner loop and exception handling should be avoided in such cases if possible.

I submit that the better place to catch that is at `toExternalObject` where the  INonExternalizableReplacementFactory should get a crack at it.

Or perhaps it could be dropped altogether. Arguably that's just hiding bugs, if it even happens...by the time we get to `choose_field`, I would expect the object to be active, and all the standard fields we use it for should be local attributes not requiring a new fetch. Are there even any occurrences of that exception (`POSKeyError` "Could not get attribute XXX for object XXX") in the logs? (@cutz?)

**Comment by cutz** [comment]
I don't see anything in any index more recent than January.  There are a bunch in bound alpha January 2018 and older.  Most recent I see in an alpha platform index is March 2016 and I'm pretty sure we've started with a fresh db more recent than that.   Most recent message in a prod index dates back to September 2015.

**Comment by jamadden** [comment]
Excellent. So we're good to remove it?

**Comment by cutz** [comment]
I'd like to follow up with @hagenrd  on the bound related ones.  I'd like to verify we did something to make them disappear and it isn't that we just haven't hit them.  I'll get back to you this morning

**Comment by cutz** [comment]
@jamadden let's go ahead and remove it.
